package middleware

import (
	"github.com/gorilla/mux"
	"net/http"
	"reiform.com/mynah/auth"
	"reiform.com/mynah/db"
	"reiform.com/mynah/settings"
)

//defines a mux which manages endpoint paths,
//authenticating users, and requesting project info
type MynahRouter struct {
	//the gorilla mux
	*mux.Router
	//the underlying http server
	server *http.Server
	//the application settings
	settings *settings.MynahSettings
	//the authentication provider for verifying jwts
	authProvider auth.AuthProvider
	//the database provider for collecting users and projects
	dbProvider db.DBProvider
}

//Response object generated by Mynah handlers
type Response struct {
	//the response body (or nil)
	Body interface{}
	//the status code
	Status int
}
